from jinja2 import Template

class EmailGenerator:
    def __init__(self, account_name, metrics, health_data):
        self.account_name = account_name
        self.metrics = metrics
        self.health_data = health_data
        self.template_str = """
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; }
        .container { width: 80%; margin: 20px auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
        .header { background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); color: white; padding: 20px; text-align: center; }
        .content { padding: 30px; }
        .health-badge { display: inline-block; padding: 5px 15px; border-radius: 20px; font-weight: bold; font-size: 0.9em; margin-bottom: 20px; }
        .status-on-track { background-color: #d4edda; color: #155724; }
        .status-stabilizing { background-color: #fff3cd; color: #856404; }
        .status-at-risk { background-color: #f8d7da; color: #721c24; }
        .metric-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 20px; margin-bottom: 30px; }
        .metric-card { background: #f9f9f9; padding: 15px; border-left: 4px solid #2a5298; border-radius: 4px; }
        .metric-value { font-size: 1.5em; font-weight: bold; color: #1e3c72; }
        .metric-label { font-size: 0.8em; color: #666; text-transform: uppercase; }
        .risk-section { background-color: #fff5f5; border: 1px solid #feb2b2; padding: 15px; border-radius: 4px; color: #c53030; }
        .footer { background: #f1f1f1; padding: 15px; text-align: center; font-size: 0.8em; color: #888; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { text-align: left; padding: 12px; border-bottom: 1px solid #eee; }
        th { background-color: #f8f8f8; color: #444; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Implementation Executive Summary</h1>
            <p>{{ account_name }} | {{ current_date }}</p>
        </div>
        <div class="content">
            <div class="health-badge status-{{ health_data.status.lower().replace(' ', '-') }}">
                {{ health_data.status }} - {{ health_data.label }}
            </div>

            <div class="metric-grid">
                <div class="metric-card">
                    <div class="metric-label">Store Coverage</div>
                    <div class="metric-value">{{ "%.1f"|format(metrics.store_coverage) }}%</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Avg. Compliance</div>
                    <div class="metric-value">{{ "%.1f"|format(metrics.avg_compliance) }}%</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Total Submissions</div>
                    <div class="metric-value">{{ metrics.total_submissions }}</div>
                </div>
                <div class="metric-card">
                    <div class="metric-label">Last Submission</div>
                    <div class="metric-value">{{ metrics.last_submission_date.split(' ')[0] }}</div>
                </div>
            </div>

            {% if health_data.risks %}
            <div class="risk-section">
                <strong>Attention Required:</strong>
                <ul>
                    {% for risk in health_data.risks %}
                    <li>{{ risk }}</li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            <h3>Weekly Progress Curve</h3>
            <table>
                <thead>
                    <tr>
                        <th>Week</th>
                        <th>Date Ending</th>
                        <th>Submissions</th>
                        <th>Coverage</th>
                        <th>Compliance</th>
                    </tr>
                </thead>
                <tbody>
                    {% for week in metrics.weekly_metrics %}
                    <tr>
                        <td>Week {{ week.week }}</td>
                        <td>{{ week.end_date }}</td>
                        <td>{{ week.cumulative_submissions }}</td>
                        <td>{{ "%.1f"|format(week.store_coverage) }}%</td>
                        <td>{{ "%.1f"|format(week.avg_compliance) }}%</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="footer">
            Generated by Taqtics Implementation Intelligence Layer.
        </div>
    </div>
</body>
</html>
"""

    def generate(self):
        from datetime import datetime
        template = Template(self.template_str)
        return template.render(
            account_name=self.account_name,
            metrics=self.metrics,
            health_data=self.health_data,
            current_date=datetime.now().strftime("%B %d, %Y")
        )
